### ISSUE TITLE
关于《软中断会吃掉你多少CPU？》中《软中断的开销估算》

### ISSUE THREAD

**Issue by sammyne** [yanfeizhang/coder-kung-fu#6]
求问 `CPU大约花费了1.2%的时钟周期在软中断上，也就是说每个核要花费12ms` 这句话的 `12ms` 是如何计算出来的，是默认时钟周期为 `1s` 吗 @yanfeizhang

**Comment by yanfeizhang** [comment]
嗯对，是按1秒来算的

Sammy ***@***.***> 于2023年10月17日周二 09:48写道：
